export default {
  active: false,
  name: 'Test | Draft 2',
  path: '/test/draft/2',
  source: 'documents/test/draft/2',
  target: 'localhost/test/draft/2',
  main: 'index.html',
  ignore: [],
  pilers: {
    sans: [{
      name: 'ClearPiler',
      type: 'sans',
      target: 'target',
      path: ['**/*.{html,css,js,md}'],
      ignore: [],
    }, {
      name: 'ClearPiler',
      type: 'sans',
      target: 'source',
      path: ['**/template.js'],
      ignore: ['**/$template.js'],
    }],
    simules: [],
    styles: [{
      name: 'SASSPiler',
      type: 'styles',
      input: 'index.scss',
      output: 'index.css',
      watch: ['**/*.scss'],
      ignore: [],
    }],
    scripts: [{
      name: 'RollupPiler',
      type: 'scripts',
      input: 'index.js',
      output: 'index.js',
      watch: ['**/*.js'],
      ignore: [
        '**/$route.js',
        '**/$document.js',
        '**/$socket.js',
      ],
      external: ['/dependencies/mvc-framework.js']
    }],
    structs: [{
      name: 'EJSPiler',
      type: 'structs',
      localsName: '$content',
      outputType: 'server',
      model: 'index.json',
      input: 'index.ejs',
      output: 'index.html',
      watch: ['**/*.{ejs,json}'],
      ignore: ['**/\$*.ejs'],
    }, {
      name: 'EJSPiler',
      type: 'structs',
      localsName: '$content',
      outputType: 'client',
      input: '**/*.ejs',
      output: '',
      watch: ['**/\$*.ejs'],
      ignore: [],
    }],
  }
}